# Generated by Django 4.0.6 on 2022-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
    ]
