# Generated by Django 4.0.6 on 2022-07-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_notify_status'),
        ('accounts', '0005_alter_account_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tenant'),
        ),
    ]
