# Generated by Django 4.0.3 on 2022-06-29 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=255)),
                ('deposit_date', models.DateField()),
                ('bill_month', models.CharField(max_length=255)),
                ('bill_year', models.CharField(max_length=255)),
                ('total_amount', models.FloatField()),
                ('deposit_method', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.BigIntegerField()),
                ('address', models.TextField()),
                ('national_id', models.BigIntegerField()),
                ('designation', models.CharField(max_length=255)),
                ('join_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salary_per_month', models.BigIntegerField()),
                ('status', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='employee/')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.BigIntegerField()),
                ('address', models.TextField()),
                ('national_id', models.BigIntegerField()),
                ('designation', models.CharField(max_length=255)),
                ('join_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='management/')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.CharField(max_length=50)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.BigIntegerField()),
                ('address', models.TextField()),
                ('national_id', models.BigIntegerField()),
                ('advance_rent', models.BigIntegerField()),
                ('rent_per_month', models.BigIntegerField()),
                ('issue_date', models.DateField()),
                ('rent_month', models.CharField(max_length=250)),
                ('rent_year', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.floor')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_month', models.CharField(max_length=255)),
                ('rent_year', models.CharField(max_length=250)),
                ('rent', models.CharField(max_length=255)),
                ('water_bill', models.BigIntegerField()),
                ('electric_bill', models.BigIntegerField()),
                ('gas_bill', models.BigIntegerField()),
                ('security_bill', models.BigIntegerField()),
                ('utility_bill', models.BigIntegerField()),
                ('other_bill', models.BigIntegerField()),
                ('total_rent', models.FloatField()),
                ('bill_paid_date', models.DateField()),
                ('status', models.CharField(max_length=250)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.floor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('salary_month', models.CharField(max_length=255)),
                ('salary_year', models.CharField(max_length=255)),
                ('salary_per_month', models.BigIntegerField()),
                ('issue_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('solution', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tenant')),
            ],
        ),
    ]
