# Generated by Django 4.0.3 on 2022-07-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_tenant_contact_remove_tenant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='name',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
