# Generated by Django 4.0.3 on 2022-07-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_notify_assigned_to_alter_notify_complain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='complain_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.tenant'),
        ),
    ]
