# Generated by Django 4.0.3 on 2022-07-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_notify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='complain_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
