# Generated by Django 4.0.3 on 2022-07-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_notify_complain_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entry_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField()),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.floor')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.unit')),
            ],
        ),
    ]
