# Generated by Django 4.0.3 on 2022-07-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='Entry_date',
            new_name='entry_date',
        ),
    ]
