# Generated by Django 4.0.3 on 2022-07-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_entry_date_visitor_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='address',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
