# Generated by Django 4.0.6 on 2022-07-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_complain_id_notify_complain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='status',
        ),
    ]
